### ISSUE TITLE
Whitelist outdated

### ISSUE THREAD

**Issue by RedSnt** [zetas/GatherBuddyImproved#5]
I've only been playing Wildstar for 9 days and only just installed GatherBuddyImproved, but already I've noticed that the whitelist is a little outdated. At first I thought the bug was that GatherBuddyImproved didn't work as expected, but then I noticed that the tree I was looking at, called "Blazing Pine" wasn't even on the whitelist.

I've been looking at the files and it doesn't seem like GatherBuddyImproved have a local DB. Would've loved it if I could add the "new stuff" manually, or possibly help update the DB. Not sure where you get the whitelist from.

**Comment by zetas** [comment]
I haven't played wildstar in ages so this add-on is very outdated. You're welcome to submit a PR to update it or just manually update it yourself. The Local DB for nodes starts here https://github.com/zetas/GatherBuddyImproved/blob/master/GatherBuddyImproved.lua#L227. Simply changing the name or adding and removing as necessary should work fine. Just make sure you maintain the same format, ['Node Name'] = true. The system loads that DB on start. 

That DB was generated with help from GBI users. People would tell me what I was missing and I added it as time went on, kind of like a wiki. 

Let me know if there's anything else I can help with.

**Comment by RedSnt** [comment]
So yeah, as I said, I'm pretty new to the game. It seems like there was some tradeskill overhaul in september: http://www.wildstar-online.com/en/news/2015-09-15-crafting-improvements-in-free-to-play/. From what I can gather from your DB it seems like there used to be 5 tiers, but I wonder if that is still true? I haven't been able to google anything with regards to maximum tiers, but assuming that the tier of any node increased per 5 levels beginning at level 10, that would mean that there are now 9 tiers.  

I'm just worried I might be adding stuff in the wrong tiers as my search here: http://www.jabbithole.com/items?f=f:27/c:110 - Increments 5 levels per tier afaik.

**Comment by zetas** [comment]
If i were you i'd look for a different plugin that did similar stuff if you're not prepared to fix this. I'm super busy at work and I don't have much interest in playing wildstar anymore, especially since it doesn't work in OSX.

**Comment by RedSnt** [comment]
I understand. I'll try and see if I can get a better grasp of the game and maybe come back with a fix for this as I advance through the tradeskill levels and tiers.
